import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./../components/Footer";
import Res_navbar from "./../components/Res_navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CampusX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Footer />
        <Res_navbar />
      </body>
    </html>
  );
}
