import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./../components/Footer";
import Header from "./../components/Header";
import ResNavbar from './../components/nav/Res_navbar';
import Navbar from './../components/nav/Navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CampusX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Navbar />
        {children}
        <Footer />
        <ResNavbar/>
      </body>
    </html>
  );
}
